#!/bin/bash

python3 main.py train --exp_name "has_distance_traveled,has_avg_stability ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_wrist_avg ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_wrist_avg ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_hand_wrist_distance ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_wrist_avg ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_wrist_avg ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_hand_wrist_distance ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_wrist_avg ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_wrist_avg ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_hand_wrist_distance ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_elbow_avg ,has_wrist_avg ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_elbow_avg ,has_hand_wrist_distance ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_elbow_avg ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_wrist_avg ,has_hand_wrist_distance ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_wrist_avg ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_hand_wrist_distance ,exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name ",exclude=["spine_joints"]" --exclude_groups '["spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_wrist_avg ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_wrist_avg ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_hand_wrist_distance ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_wrist_avg ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_wrist_avg ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_hand_wrist_distance ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_wrist_avg ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_wrist_avg ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_hand_wrist_distance ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_elbow_avg ,has_wrist_avg ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_elbow_avg ,has_hand_wrist_distance ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_elbow_avg ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_wrist_avg ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_hand_wrist_distance ,exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name ",exclude=["head_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["head_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_wrist_avg ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_wrist_avg ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_hand_wrist_distance ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_wrist_avg ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_wrist_avg ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_hand_wrist_distance ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_wrist_avg ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_wrist_avg ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_hand_wrist_distance ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_elbow_avg ,has_wrist_avg ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_elbow_avg ,has_hand_wrist_distance ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_elbow_avg ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_wrist_avg ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_hand_wrist_distance ,exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name ",exclude=["head_joints", "leg_joints", "spine_joints"]" --exclude_groups '["head_joints", "leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_wrist_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_wrist_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_wrist_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_wrist_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_wrist_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_wrist_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_elbow_avg ,has_wrist_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_elbow_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_elbow_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_wrist_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name ",exclude=["leg_joints", "spine_joints", "thorax_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_wrist_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_wrist_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_wrist_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_wrist_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_wrist_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_wrist_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_elbow_avg ,has_wrist_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_elbow_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_elbow_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_wrist_avg ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name ",exclude=["leg_joints", "spine_joints", "thorax_joints", "head_joints"]" --exclude_groups '["leg_joints", "spine_joints", "thorax_joints", "head_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_wrist_avg ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_wrist_avg ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_hand_wrist_distance ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_wrist_avg ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_wrist_avg ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_hand_wrist_distance ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_wrist_avg ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_wrist_avg ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_hand_wrist_distance ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_elbow_avg ,has_wrist_avg ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_elbow_avg ,has_hand_wrist_distance ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_elbow_avg ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_wrist_avg ,has_hand_wrist_distance ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_wrist_avg ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_hand_wrist_distance ,exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name ",exclude=["head_joints", "thorax_joints"]" --exclude_groups '["head_joints", "thorax_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_wrist_avg ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_elbow_avg ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_wrist_avg ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_avg_stability ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_wrist_avg ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_elbow_avg ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,has_wrist_avg ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_distance_traveled ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_distance_traveled ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=True --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_wrist_avg ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_elbow_avg ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,has_wrist_avg ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_avg_stability ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_avg_stability ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=True --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_elbow_avg ,has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_elbow_avg ,has_wrist_avg ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_elbow_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_elbow_avg ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=True --has_wrist_avg=False --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_wrist_avg ,has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=True
python3 main.py train --exp_name "has_wrist_avg ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=True --has_hand_wrist_distance=False
python3 main.py train --exp_name "has_hand_wrist_distance ,exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=True
python3 main.py train --exp_name ",exclude=["leg_joints", "spine_joints"]" --exclude_groups '["leg_joints", "spine_joints"]' --has_distance_traveled=False --has_avg_stability=False --has_elbow_avg=False --has_wrist_avg=False --has_hand_wrist_distance=False
